# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p4wifi/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

# Custom Ganbarou packages
PRODUCT_PACKAGES += \
    Wallpapers

PRODUCT_COPY_FILES := \
    vendor/samsung/p4wifi/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/samsung/p4wifi/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    vendor/samsung/p4wifi/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
    vendor/samsung/p4wifi/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so

PRODUCT_COPY_FILES += \
    vendor/samsung/p4wifi/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/p4wifi/proprietary/bin/nvrm_daemon:system/bin/nvrm_daemon \
    vendor/samsung/p4wifi/proprietary/bin/tegrastats:system/bin/tegrastats \
    vendor/samsung/p4wifi/proprietary/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/p4wifi/proprietary/etc/firmware/bcm4330B1.hcd:system/etc/firmware/bcm4330B1.hcd \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_h264dec2x.axf:system/etc/firmware/nvmm_h264dec2x.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_mpeg2dec.axf:system/etc/firmware/nvmm_mpeg2dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/samsung/p4wifi/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/samsung/p4wifi/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/p4wifi/proprietary/etc/wifi/wl:system/etc/wifi/wl \
    vendor/samsung/p4wifi/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/p4wifi/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/lights.p3.so:system/lib/hw/lights.p3.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/overlay.tegra.so:system/lib/hw/overlay.tegra.so \
    vendor/samsung/p4wifi/proprietary/lib/hw/sensors.p3.so:system/lib/hw/sensors.p3.so \
    vendor/samsung/p4wifi/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
    vendor/samsung/p4wifi/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/p4wifi/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/p4wifi/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/samsung/p4wifi/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/samsung/p4wifi/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    vendor/samsung/p4wifi/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/samsung/p4wifi/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/samsung/p4wifi/proprietary/lib/liblvvefs.so:system/lib/liblvvefs.so \
    vendor/samsung/p4wifi/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/p4wifi/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/samsung/p4wifi/proprietary/lib/libmpl.so:system/lib/libmpl.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvstereoutils_jni.so:system/lib/libnvstereoutils_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/samsung/p4wifi/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/samsung/p4wifi/proprietary/lib/libPanoraMax3.so:system/lib/libPanoraMax3.so \
    vendor/samsung/p4wifi/proprietary/lib/libsamsungAcousticeq.so:system/lib/libsamsungAcousticeq.so \
    vendor/samsung/p4wifi/proprietary/lib/lib_Samsung_Acoustic_Module_Llite.so:system/lib/lib_Samsung_Acoustic_Module_Llite.so \
    vendor/samsung/p4wifi/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/p4wifi/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/p4wifi/proprietary/lib/lib_Samsung_Sound_Booster.so:system/lib/lib_Samsung_Sound_Booster.so \
    vendor/samsung/p4wifi/proprietary/lib/libseccameraadaptor.so:system/lib/libseccameraadaptor.so \
    vendor/samsung/p4wifi/proprietary/lib/libseccamera.so:system/lib/libseccamera.so \
    vendor/samsung/p4wifi/proprietary/lib/libsecjpegencoder.so:system/lib/libsecjpegencoder.so \
    vendor/samsung/p4wifi/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/p4wifi/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/p4wifi/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/p4wifi/proprietary/lib/omxplayer.so:system/lib/omxplayer.so 
# Samsung files
PRODUCT_COPY_FILES += \
    vendor/samsung/p4wifi/proprietary/app/PolarisOffice.apk:system/app/PolarisOffice.apk \
    vendor/samsung/p4wifi/proprietary/apps/SamsungAppsUNAService.apk:system/apps/SamsungAppsUNAService.apk \
    vendor/samsung/p4wifi/proprietary/etc/permissions/touchwiz.xml:system/etc/permissions/touchwiz.xml \
    vendor/samsung/p4wifi/proprietary/framework/twframework.jar:system/framework/twframework.jar \
    vendor/samsung/p4wifi/proprietary/framework/twframework-res.apk:system/framework/twframework-res.apk \
    vendor/samsung/p4wifi/proprietary/framework/secmediarecorder.jar:system/framework/secmediarecorder.jar \
    vendor/samsung/p4wifi/proprietary/lib/libglcanvas.so:system/lib/libglcanvas.so \
    vendor/samsung/p4wifi/proprietary/lib/libpolarisoffice.so:system/lib/libpolarisoffice.so 
# GApps
PRODUCT_COPY_FILES += \
    vendor/samsung/p4wifi/proprietary/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/samsung/p4wifi/proprietary/app/ChromeBookmarksSyncAdapter.apk:system/app/ChromeBookmarksSyncAdapter.apk \
    vendor/samsung/p4wifi/proprietary/app/GalleryGoogle.apk:system/app/GalleryGoogle.apk \
    vendor/samsung/p4wifi/proprietary/app/GenieWidget.apk:system/app/GenieWidget.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleBackupTransport.apk:system/app/GoogleBackupTransport.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleLoginService.apk:system/app/GoogleLoginService.apk \
    vendor/samsung/p4wifi/proprietary/app/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleQuickSearchBox.apk:system/app/GoogleQuickSearchBox.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/samsung/p4wifi/proprietary/app/GoogleTTS.apk:system/app/GoogleTTS.apk \
    vendor/samsung/p4wifi/proprietary/app/MarketUpdater.apk:system/app/MarketUpdater.apk \
    vendor/samsung/p4wifi/proprietary/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/samsung/p4wifi/proprietary/app/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/samsung/p4wifi/proprietary/app/OneTimeInitializer.apk:system/app/OneTimeInitializer.apk \
    vendor/samsung/p4wifi/proprietary/app/Phonesky.apk:system/app/Phonesky.apk \
    vendor/samsung/p4wifi/proprietary/app/SetupWizard.apk:system/app/SetupWizard.apk \
    vendor/samsung/p4wifi/proprietary/app/Talk.apk:system/app/Talk.apk \
    vendor/samsung/p4wifi/proprietary/app/VoiceSearch.apk:system/app/VoiceSearch.apk \
    vendor/samsung/p4wifi/proprietary/etc/g.prop:system/etc/g.prop \
    vendor/samsung/p4wifi/proprietary/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/samsung/p4wifi/proprietary/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/samsung/p4wifi/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/samsung/p4wifi/proprietary/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/samsung/p4wifi/proprietary/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/samsung/p4wifi/proprietary/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/samsung/p4wifi/proprietary/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/samsung/p4wifi/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/samsung/p4wifi/proprietary/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
    vendor/samsung/p4wifi/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/samsung/p4wifi/proprietary/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libpicowrapper.so:system/lib/libpicowrapper.so \
    vendor/samsung/p4wifi/proprietary/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/samsung/p4wifi/proprietary/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    vendor/samsung/p4wifi/proprietary/lib/libvideochat_stabilize.so:system/lib/libvideochat_stabilize.so \
    vendor/samsung/p4wifi/proprietary/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/de-DE_gl0_sg.bin:system/tts/lang_pico/de-DE_gl0_sg.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/de-DE_ta.bin:system/tts/lang_pico/de-DE_ta.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/fr-FR_nk0_sg.bin:system/tts/lang_pico/fr-FR_nk0_sg.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/fr-FR_ta.bin:system/tts/lang_pico/fr-FR_ta.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/it-IT_cm0_sg.bin:system/tts/lang_pico/it-IT_cm0_sg.bin \
    vendor/samsung/p4wifi/proprietary/tts/lang_pico/it-IT_ta.bin:system/tts/lang_pico/it-IT_ta.bin 

